on: push
name: Reproducibility Check

jobs:
  render:
    name: execute notebook
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Dependencies
        run: pip install -e requirements.txt
      - name: test
        run: pytest --nbval-lax climate.ipynb
